<?php
    // 尝试链接mysql服务器 
    $connection = mysqli_connect("rerun.it.uts.edu.au","potiro","pcXZb(kL","poti");
    if( !$connection ) {
        echo "mysql server is conneted...";
    }
    // $sql = "SELECT * FROM products";
    // $result = mysqli_query($connection, $sql);
    // $numOfRows = mysqli_num_rows($result);
    // $i = 0; 
    // $product_list = array();
    // while( $i < $numOfRows) {
    //     array_push($product_list, mysqli_fetch_assoc($result) );
    //     $i++;
    // }
    // mysqli_free_result($result);
    // mysqli_close($conn);
    
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="./public/css/styles.css">
</head>
<body>  
    <div class="category">
        <a href="./cart.php" target="cart">show cart</a> 
        <a href="./user.php" target="user" >show order</a>
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="./public/img/cate.png" usemap="#image-map">

        <map name="image-map">
            <area class="categories" target="" alt="frozen-food" title="frozen-food" href="" coords="7,144,83,183" shape="rect">
            <area class="categories" target="" alt="fresh-food" title="fresh-food" href="" coords="102,144,184,183" shape="rect">
            <area class="categories" target="" alt="beverages" title="beverages" href="" coords="199,144,277,181" shape="rect">
            <area class="categories"target="" alt="home-health" title="home-health" href="" coords="289,144,375,181" shape="rect">
            <area class="categories" target="" alt="pet-food" title="pet-food" href="" coords="388,142,468,180" shape="rect">
        </map>

        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img id="sub-category" src="./public/img/empty.png" usemap="#pet-food">

        <map name="pet-food">
            <area alt="bird-food" target="cart" title="bird-food" href="cart.php?product_id=5002" coords="103,132,185,174" shape="rect">
            <area alt="cat-food" target="cart" title="cat-food"  coords="201,134,279,172"  href="cart.php?product_id=5003" shape="rect">
            <area alt="dry-dog-1kg" target="cart" title="dry-dog-1kg"  coords="259,249,337,288" href="cart.php?product_id=5001" shape="rect">
            <area alt="dry-dog-5kg" target="cart" title="dry-dog-5kg"  coords="351,247,433,291" href="cart.php?product_id=5000" shape="rect">
            <area alt="fish-food"  target="cart" title="fish-food" coords="473,171,390,131" href="cart.php?product_id=5004" shape="rect">
        </map>


    </div>
    <div class="user">
        <iframe name="cart" src="" ></iframe>
        <iframe name="user" src="" ></iframe>
    </div>
    
    
    
    <script>
        var areas = document.querySelectorAll('.categories') // 搜索全部带有"cate-main" class的元素
        var subarea = document.querySelector('#sub-category') // 找到带有“sub-category"id 的元素，也就是那张空白图片

        areas.forEach(function(area, idx) { // 遍历全部的area
            area.addEventListener('click', function(event) {//给每个area加上一个点击事件
                console.log(event)
                
                showImg(event) //在每次用户点击时图片热区是，调用这个方法
            })
        })

        var showImg = function(event) { 
            event.preventDefault();
            var categoryName = event.target.title // 因为area标签中有title这个属性，找到它
            subarea.src = `./public/img/${categoryName}.png` // 把空白图片的地址换成选择好的地址
        }
    
    </script>
</body>
</html>
