<?php
    // 尝试链接mysql服务器 
    $connection = mysqli_connect("rerun.it.uts.edu.au","potiro","pcXZb(kL","poti");
    if( !$connection ) {
        echo "mysql server is conneted...";
    }
    // $sql = "SELECT * FROM products";
    // $result = mysqli_query($connection, $sql);
    // $numOfRows = mysqli_num_rows($result);
    // $i = 0; 
    // $product_list = array();
    // while( $i < $numOfRows) {
    //     array_push($product_list, mysqli_fetch_assoc($result) );
    //     $i++;
    // }
    // mysqli_free_result($result);
    // mysqli_close($conn);
    
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            height: 100%;
        }
        main{
            display:flex;
            flex-direction: row;
            min-height:100vh;
        }
        .category{
            width: 49%;
            float:left;
            background-color: #D8E2DC;
        }

        .category img {
            max-width: none;
        }

        .user {
            width:49%;
            height: 100vh;
            float:right;
            flex:1;
            /* flex-grow:0;  */
            flex-direction: column;
            justify-content: space-between;
            position: relative;
        }
        
        .cart{
           flex-grow:3;
           width: 100%;
           height: 20vh;
           background-color: #FFCAD4;
           position: relative;
        }

        .cart iframe {
            top: 0;
            width: 100%;
            border:1px;
        }


        .order{
           flex-grow: 2; 
           width:100%;
           height: 75vh;
           position: relative;
           background-color: #FFE5D9;
        }

        .order iframe {
            width: 100%;
            height: 100%;
            bottom: 0;
            border: 1px;
        }
        
        /* iframe {
            width: 100%;
            height: 100%;
            position: absolute;
            display:block;
            top:0;
            left:0;
        } */
    </style>
</head>
<body>
    <main>  
    <div class="category">
        <!-- <a href="./cart.php" target="cart">show cart</a> 
        <a href="./user.php" target="order" >show order</a> -->
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="./public/img/cate.png" usemap="#image-map">

        <map name="image-map">
            <area class="categories" target="" alt="frozen-food" title="frozen-food" href="" coords="7,144,83,183" shape="rect">
            <area class="categories" target="" alt="fresh-food" title="fresh-food" href="" coords="102,144,184,183" shape="rect">
            <area class="categories" target="" alt="beverages" title="beverages" href="" coords="199,144,277,181" shape="rect">
            <area class="categories"target="" alt="home-health" title="home-health" href="" coords="289,144,375,181" shape="rect">
            <area class="categories" target="" alt="pet-food" title="pet-food" href="" coords="388,142,468,180" shape="rect">
        </map>

        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img id="sub-category" src="./public/img/empty.png" usemap="">

        <map name="pet-food">
            <area alt="bird-food" target="cart" title="bird-food" href="cart.php?product_id=5002" coords="103,132,185,174" shape="rect">
            <area alt="cat-food" target="cart" title="cat-food"  coords="201,134,279,172"  href="cart.php?product_id=5003" shape="rect">
            <area alt="dry-dog-1kg" target="cart" title="dry-dog-1kg"  coords="259,249,337,288" href="cart.php?product_id=5001" shape="rect">
            <area alt="dry-dog-5kg" target="cart" title="dry-dog-5kg"  coords="351,247,433,291" href="cart.php?product_id=5000" shape="rect">
            <area alt="fish-food"  target="cart" title="fish-food" coords="473,171,390,131" href="cart.php?product_id=5004" shape="rect">
        </map>


        <!-- Image Map Generated by http://www.image-map.net/ -->


        <map name="beverages">
            <area target="" alt="" title="" href="" coords="24,244,86,283" shape="rect">
            <area target="" alt="" title="" href="" coords="90,248,154,283" shape="rect">
            <area target="" alt="" title="" href="" coords="163,249,221,280" shape="rect">
            <area target="" alt="" title="" href="" coords="233,244,297,281" shape="rect">
            <area target="" alt="" title="" href="" coords="307,246,365,276" shape="rect">
            <area target="" alt="" title="" href="" coords="399,141,479,175" shape="rect">
        </map>


    </div>
    <div class="user">
        <div class="cart">
            <iframe name="cart" src=""></iframe>
        </div>
        <div class="order">
            <iframe name="order" src=""></iframe>
        </div>
    </div>
    </main>
    
    
    <script>
        var areas = document.querySelectorAll('.categories') // 搜索全部带有"cate-main" class的元素
        var subarea = document.querySelector('#sub-category') // 找到带有“sub-category"id 的元素，也就是那张空白图片

        areas.forEach(function(area, idx) { // 遍历全部的area
            area.addEventListener('click', function(event) {//给每个area加上一个点击事件
                // console.log(event)
                showImg(event) //在每次用户点击时图片热区是，调用这个方法
            })
        })

        var showImg = function(event) { 
            event.preventDefault();
            var categoryName = event.target.title // 因为area标签中有title这个属性，找到它
            subarea.src = `./public/img/${categoryName}.png` // 把空白图片的地址换成选择好的地址
            subarea.setAttribute("usemap", `#${categoryName}`)
        }
    
    </script>
</body>
</html>